const JOBS_KEY="postular.jobs.v2", PREFS_KEY="postular.preferences.v2", THEME_KEY="postular.theme";
const $=id=>document.getElementById(id);
const defaults={salary:800000,travel:60,location:"San Miguel",experience:2,keywords:"soporte, help desk, frontend, react, javascript, qa, testing, data entry, administrativo, excel",modes:["Remoto","Híbrido"],noWeekends:true,junior:true};
let jobs=read(JOBS_KEY,read("postular.jobs.v1",[])).map(normalizeJob),prefs={...defaults,...read(PREFS_KEY,{})},current=null;
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(){localStorage.setItem(JOBS_KEY,JSON.stringify(jobs));renderJobs();updateStats()}
function norm(s=""){return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function money(v){const n=Number(String(v||"").replace(/\D/g,""));return n||0}
function esc(s=""){return String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function validUrl(u){try{return ["http:","https:"].includes(new URL(u).protocol)}catch{return false}}
function normalizeJob(j){return{id:j.id||crypto.randomUUID(),company:j.company||"Empresa no informada",role:j.role||"Puesto no informado",platform:j.platform||"Otra",mode:j.mode||"No informada",location:j.location||"",salary:j.salary||"",url:j.url||"",description:j.description||"",notes:j.notes||"",score:Number(j.score)||0,verdict:j.verdict||"Revisar",matches:j.matches||[],alerts:j.alerts||[],questions:j.questions||[],status:j.status||"Pendiente",createdAt:j.createdAt||new Date().toISOString(),appliedDate:j.appliedDate||"",followUpDate:j.followUpDate||""}}
function formData(){return{company:$("company").value.trim(),role:$("role").value.trim(),platform:$("platform").value,mode:$("mode").value,location:$("location").value.trim(),salary:$("salary").value.trim(),url:$("url").value.trim(),description:$("description").value.trim(),notes:$("notes").value.trim(),appliedDate:$("appliedDate").value,followUpDate:$("followUpDate").value}}
function analyze(d){const text=norm(`${d.role} ${d.description}`),matches=[],alerts=[],questions=[];let score=38;const keys=prefs.keywords.split(",").map(x=>norm(x.trim())).filter(Boolean);const found=[...new Set(keys.filter(k=>text.includes(k)))];if(found.length){score+=Math.min(30,found.length*6);matches.push(...found.slice(0,6).map(titleCase))}else{alerts.push("No se detectaron tus roles o habilidades prioritarias");score-=12}if(prefs.modes.includes(d.mode)){score+=12;matches.push(`Modalidad ${d.mode.toLowerCase()}`)}else if(d.mode==="No informada")questions.push("Modalidad no informada");else{alerts.push(`La modalidad ${d.mode.toLowerCase()} no está entre tus preferidas`);score-=5}const sal=money(d.salary);if(sal){if(sal>=prefs.salary){score+=12;matches.push("Sueldo dentro del objetivo")}else{score-=12;alerts.push(`Sueldo inferior a $${prefs.salary.toLocaleString("es-AR")}`)}}else questions.push("Sueldo no informado");const exp=[...text.matchAll(/(\d+)\s*(?:anos|año|años)\s*(?:de\s*)?experiencia/g)].map(m=>Number(m[1]));if(exp.length&&Math.min(...exp)>Number(prefs.experience)){score-=14;alerts.push(`Solicita ${Math.min(...exp)} años de experiencia`)}else if(/sin experiencia|trainee|junior|jr\b/.test(text)){score+=8;matches.push("Nivel inicial compatible")}if(prefs.noWeekends&&/sabado|domingo|fin(?:es)? de semana|franco rotativo/.test(text)){score-=12;alerts.push("Podría requerir fines de semana o francos rotativos")}if(/ingles (?:avanzado|bilingue)|advanced english|b2|c1|c2/.test(text)){score-=5;alerts.push("Revisar nivel de inglés requerido")}if(d.mode==="Presencial"&&!d.location)questions.push("Ubicación no informada");if(d.mode==="Presencial"&&d.location)questions.push(`Confirmar viaje máximo de ${prefs.travel} minutos desde ${prefs.location}`);if(!/horario|jornada|lunes|viernes|full time|part time/.test(text))questions.push("Horario no informado");score=Math.max(0,Math.min(100,score));const verdict=score>=75?"POSTULAR":score>=52?"POSTULAR CON RESERVAS":"NO PRIORIZAR";return{score,verdict,matches,alerts,questions}}
function titleCase(s){return s.replace(/\b\w/g,c=>c.toUpperCase())}
function showResult(d,a){current={...d,...a};const cls=a.score>=75?"":a.score>=52?"warn":"no";$("result").innerHTML=`<div class="score-head"><div><span class="verdict ${cls}">${a.verdict}</span><h2>${esc(d.role||"Oferta analizada")}</h2><p class="result-meta">${esc(d.company||"Empresa no informada")}</p></div><div class="score-ring" style="--score:${a.score}"><strong>${a.score}</strong></div></div>${section("Coincidencias",a.matches,"No se detectaron coincidencias claras")}${section("Alertas",a.alerts,"Sin alertas importantes")}${section("Preguntas pendientes",a.questions,"La oferta aporta los datos principales")}${validUrl(d.url)?`<a class="primary" href="${esc(d.url)}" target="_blank" rel="noopener">Abrir oferta original ↗</a>`:""}<button class="primary" id="saveCurrent" type="button">${$("editingId").value?"Guardar cambios":"Guardar en seguimiento"}</button>`;$("saveCurrent").onclick=saveCurrent}
function section(t,items,empty){return`<h3>${t}</h3><ul>${items.length?items.map(x=>`<li>${esc(x)}</li>`).join(""):`<li>${empty}</li>`}</ul>`}
$("evaluationForm").addEventListener("submit",e=>{e.preventDefault();const d=formData();if(d.url&&!validUrl(d.url)){toast("Revisá el enlace de la oferta");return}showResult(d,analyze(d))});
function saveCurrent(){if(!current)return;const id=$("editingId").value;const duplicate=jobs.find(j=>j.id!==id&&((current.url&&j.url===current.url)||(norm(j.company)===norm(current.company)&&norm(j.role)===norm(current.role))));if(duplicate&&!confirm("Esta oferta parece estar guardada. ¿Querés guardarla igualmente?"))return;if(id){const old=jobs.find(j=>j.id===id);jobs=jobs.map(j=>j.id===id?normalizeJob({...old,...current,id,status:old.status}):j);toast("Oferta actualizada")}else{jobs.unshift(normalizeJob({...current,id:crypto.randomUUID(),createdAt:new Date().toISOString()}));toast("Oferta guardada")}save();resetForm();switchTab("track")}
function editJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;for(const k of ["company","role","platform","mode","location","salary","url","description","notes","appliedDate","followUpDate"])$(k).value=j[k]||"";$("editingId").value=id;$("analyzeLabel").textContent="Reanalizar y guardar";$("cancelEdit").classList.remove("hidden");showResult(j,j);switchTab("evaluate");scrollTo({top:0,behavior:"smooth"})}
function resetForm(){$("evaluationForm").reset();$("editingId").value="";$("analyzeLabel").textContent="Analizar oferta";$("cancelEdit").classList.add("hidden");current=null;renderEmptyResult()}
$("cancelEdit").onclick=resetForm;$("newJob").onclick=()=>{resetForm();switchTab("evaluate")};
function due(j){return j.followUpDate&&j.followUpDate<today()&&!['Rechazado','Contratado'].includes(j.status)}function today(){return new Date().toISOString().slice(0,10)}
function renderJobs(){const q=norm($("search").value),filter=$("statusFilter").value,sort=$("sortBy").value;let list=jobs.filter(j=>(filter==="Todos"||j.status===filter)&&norm(`${j.company} ${j.role} ${j.notes}`).includes(q));list.sort((a,b)=>sort==="score"?b.score-a.score:sort==="followup"?(a.followUpDate||"9999").localeCompare(b.followUpDate||"9999"):new Date(b.createdAt)-new Date(a.createdAt));$("jobList").innerHTML=list.length?list.map(j=>`<article class="card job"><div class="job-main"><div class="job-top"><h2>${esc(j.role)}</h2><span class="badge">${j.score}/100</span>${due(j)?'<span class="badge overdue">Seguimiento vencido</span>':''}</div><p><strong>${esc(j.company)}</strong> · ${esc(j.mode)}${j.location?` · ${esc(j.location)}`:""}</p><p>${j.followUpDate?`Seguimiento: ${formatDate(j.followUpDate)}`:"Sin seguimiento programado"}${j.notes?` · ${esc(j.notes)}`:""}</p></div><div class="job-actions"><select data-status="${j.id}" aria-label="Estado de ${esc(j.role)}">${["Pendiente","Postulado","Entrevista","Prueba técnica","Oferta","Rechazado","Contratado"].map(s=>`<option ${s===j.status?"selected":""}>${s}</option>`).join("")}</select>${validUrl(j.url)?`<a href="${esc(j.url)}" target="_blank" rel="noopener">Abrir ↗</a>`:""}<button data-edit="${j.id}">Editar</button><button data-delete="${j.id}">Eliminar</button></div></article>`).join(""):'<div class="card empty-list">No hay ofertas que coincidan con este filtro.</div>';document.querySelectorAll("[data-status]").forEach(x=>x.onchange=()=>{const j=jobs.find(y=>y.id===x.dataset.status);j.status=x.value;if(x.value==="Postulado"&&!j.appliedDate)j.appliedDate=today();save()});document.querySelectorAll("[data-edit]").forEach(x=>x.onclick=()=>editJob(x.dataset.edit));document.querySelectorAll("[data-delete]").forEach(x=>x.onclick=()=>{if(confirm("¿Eliminar esta oferta del seguimiento?")){jobs=jobs.filter(j=>j.id!==x.dataset.delete);save();toast("Oferta eliminada")}})}
function formatDate(s){return new Date(`${s}T12:00:00`).toLocaleDateString("es-AR")}
function updateStats(){$("navCount").textContent=jobs.length;$("totalStat").textContent=jobs.length;$("appliedStat").textContent=jobs.filter(j=>j.status!=="Pendiente").length;$("interviewStat").textContent=jobs.filter(j=>["Entrevista","Prueba técnica","Oferta"].includes(j.status)).length;$("overdueStat").textContent=jobs.filter(due).length}
[$("search"),$("statusFilter"),$("sortBy")].forEach(x=>x.addEventListener(x.tagName==="INPUT"?"input":"change",renderJobs));
function download(name,text,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("exportJson").onclick=()=>download(`postular-respaldo-${today()}.json`,JSON.stringify({version:2,exportedAt:new Date().toISOString(),preferences:prefs,jobs},null,2),"application/json");
$("exportCsv").onclick=()=>{const cols=["Empresa","Puesto","Estado","Compatibilidad","Modalidad","Ubicación","Sueldo","Fecha postulación","Seguimiento","Enlace","Notas"];const rows=jobs.map(j=>[j.company,j.role,j.status,j.score,j.mode,j.location,j.salary,j.appliedDate,j.followUpDate,j.url,j.notes]);download(`postular-${today()}.csv`,"\ufeff"+[cols,...rows].map(r=>r.map(v=>`"${String(v||"").replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv;charset=utf-8")};
$("importJson").onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text()),incoming=Array.isArray(data)?data:data.jobs;if(!Array.isArray(incoming))throw Error();jobs=incoming.map(normalizeJob);if(data.preferences){prefs={...defaults,...data.preferences};localStorage.setItem(PREFS_KEY,JSON.stringify(prefs));loadPrefs()}save();toast("Respaldo importado")}catch{toast("El archivo no es un respaldo válido")}e.target.value=""};
function loadPrefs(){$("prefSalary").value=prefs.salary;$("prefTravel").value=prefs.travel;$("prefLocation").value=prefs.location;$("prefExperience").value=String(prefs.experience);$("prefKeywords").value=prefs.keywords;$("prefNoWeekends").checked=prefs.noWeekends;$("prefJunior").checked=prefs.junior;document.querySelectorAll('[name="preferredMode"]').forEach(x=>x.checked=prefs.modes.includes(x.value));renderEmptyResult()}
$("settingsForm").onsubmit=e=>{e.preventDefault();prefs={salary:Number($("prefSalary").value)||0,travel:Number($("prefTravel").value)||0,location:$("prefLocation").value.trim(),experience:Number($("prefExperience").value),keywords:$("prefKeywords").value.trim(),modes:[...document.querySelectorAll('[name="preferredMode"]:checked')].map(x=>x.value),noWeekends:$("prefNoWeekends").checked,junior:$("prefJunior").checked};localStorage.setItem(PREFS_KEY,JSON.stringify(prefs));renderEmptyResult();toast("Preferencias guardadas")};
$("clearData").onclick=()=>{if(confirm("¿Seguro? Se borrarán todas las ofertas y preferencias guardadas en este navegador.")){localStorage.removeItem(JOBS_KEY);localStorage.removeItem("postular.jobs.v1");localStorage.removeItem(PREFS_KEY);jobs=[];prefs={...defaults};save();loadPrefs();toast("Datos eliminados")}};
function renderEmptyResult(){const items=[`Objetivo desde $${Number(prefs.salary).toLocaleString("es-AR")}`,`Hasta ${prefs.travel} minutos desde ${prefs.location}`,prefs.noWeekends?"Sin fines de semana":"Fines de semana aceptados",`${prefs.modes.join(" / ")||"Cualquier modalidad"}`];$("priorityPreview").innerHTML=items.map(x=>`<li>${esc(x)}</li>`).join("");if(!current)$("result").innerHTML=`<div class="empty"><div>◎</div><h2>Tu evaluación aparecerá acá</h2><p>Compara requisitos, modalidad, experiencia, sueldo y condiciones.</p><ul id="priorityPreview">${items.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div>`}
function switchTab(id){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x.dataset.tab===id));if(id==="track")renderJobs()}
document.querySelectorAll("[data-tab]").forEach(x=>x.onclick=()=>switchTab(x.dataset.tab));
function applyTheme(t){document.documentElement.dataset.theme=t;$("themeToggle").textContent=t==="dark"?"☀":"☾";localStorage.setItem(THEME_KEY,t)}$("themeToggle").onclick=()=>applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark");
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),2600)}
applyTheme(localStorage.getItem(THEME_KEY)||((matchMedia("(prefers-color-scheme: dark)").matches)?"dark":"light"));loadPrefs();renderJobs();updateStats();
