const KEY="postular.jobs.v1";
const $=id=>document.getElementById(id);
let jobs=[],current=null;
try{jobs=JSON.parse(localStorage.getItem(KEY)||"[]")}catch{jobs=[]}
const priorities=[["soporte",15,"Soporte técnico"],["help desk",15,"Help desk"],["frontend",16,"Desarrollo frontend"],["react",13,"React"],["javascript",10,"JavaScript"],["qa",14,"QA / testing"],["data entry",13,"Data entry"],["administrativ",11,"Administración"],["analista de datos",14,"Análisis de datos"],["sql",10,"SQL"],["python",10,"Python"],["excel",8,"Excel"],["trainee",14,"Nivel trainee"],["junior",12,"Nivel junior"],["sistemas",9,"Sistemas"]];
const blockers=[["inglés avanzado",-22,"Exige inglés avanzado"],["english advanced",-22,"Exige inglés avanzado"],["venta en frío",-24,"Venta en frío"],["comisionista",-22,"Trabajo a comisión"],["fines de semana",-18,"Requiere fines de semana"],["sábado y domingo",-22,"Requiere sábado y domingo"],["senior",-25,"Nivel senior"],["semi senior",-15,"Nivel semi senior"],["3 años de experiencia",-18,"Pide 3 años de experiencia"],["5 años de experiencia",-28,"Pide 5 años de experiencia"]];
function formData(){return{company:$("company").value,role:$("role").value,platform:$("platform").value,url:$("url").value,location:$("location").value,mode:$("mode").value,salary:$("salary").value,text:$("description").value}}
function evaluate(f){const t=(f.role+" "+f.location+" "+f.mode+" "+f.salary+" "+f.text).toLowerCase();let score=42;const good=[],warnings=[],questions=[];
priorities.forEach(([k,n,l])=>{if(t.includes(k)){score+=n;if(!good.includes(l))good.push(l)}});blockers.forEach(([k,n,l])=>{if(t.includes(k)){score+=n;if(!warnings.includes(l))warnings.push(l)}});
if(/remot[oa]/.test(t)){score+=10;good.push("Modalidad remota")}if(/h.brid[oa]/.test(t)){score+=5;good.push("Modalidad híbrida")}if(/sin experiencia|primer empleo/.test(t)){score+=15;good.push("No exige experiencia previa")}
if(/atención al cliente|call center|telemarketing/.test(t)){score-=10;warnings.push("Orientación a atención al cliente")}if(/depósito|carga y descarga|operario/.test(t)){score-=12;warnings.push("Perfil operativo de baja prioridad")}if(/presencial/.test(t)&&!t.includes("san miguel"))warnings.push("Confirmar viaje máximo de 1 hora desde San Miguel");
const salary=Number(f.salary.replace(/[^0-9]/g,""));if(salary&&salary<800000){score-=22;warnings.push("Sueldo inferior a $800.000")}if(salary>=800000){score+=8;good.push("Sueldo dentro del objetivo")}if(!f.salary)questions.push("Sueldo no informado");if(!/horario|jornada|lunes|viernes/.test(t))questions.push("Horario no informado");if(!/experiencia/.test(t))questions.push("Experiencia requerida poco clara");
score=Math.max(0,Math.min(100,score));return{score,decision:score>=68?"POSTULAR":score>=45?"POSTULAR CON RESERVAS":"NO POSTULAR",good:[...new Set(good)].slice(0,7),warnings:[...new Set(warnings)].slice(0,7),questions}}
function list(title,items,kind,empty){return `<div class="list"><h3>${title}</h3><ul class="${kind}">${(items.length?items:[empty]).map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul></div>`}
function renderResult(){const r=current;if(!r)return;const cls=r.score>=68?"yes":r.score>=45?"maybe":"no";$("result").innerHTML=`<div class="decision ${cls}"><small>RECOMENDACIÓN</small><strong>${r.decision}</strong><span>${r.score}/100 de compatibilidad</span></div><div class="bar"><i style="width:${r.score}%"></i></div>${list("Coincidencias",r.good,"good","Sin coincidencias claras.")}${list("Alertas",r.warnings,"warn","Sin alertas importantes.")}${list("Preguntas pendientes",r.questions,"ask","La información principal está disponible.")}<button class="save" id="saveJob">Guardar en seguimiento</button>`;$("saveJob").onclick=saveJob}
$("evaluationForm").onsubmit=e=>{e.preventDefault();const f=formData();if(!f.text.trim())return toast("Pegá la descripción");current={...evaluate(f),form:f};renderResult()}
function saveJob(){const j={id:crypto.randomUUID(),date:new Date().toISOString(),...current.form,status:"Pendiente",evaluation:{decision:current.decision,score:current.score,good:current.good,warnings:current.warnings,questions:current.questions}};jobs.unshift(j);persist();$("evaluationForm").reset();current=null;toast("Oferta guardada");showTab("track")}
function persist(){localStorage.setItem(KEY,JSON.stringify(jobs));renderJobs()}
function showTab(id){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x.dataset.tab===id));if(id==="track")renderJobs()}
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$("newJob").onclick=()=>showTab("evaluate");
function renderJobs(){const q=$("search").value.toLowerCase(),filter=$("statusFilter").value;const shown=jobs.filter(j=>(j.company+" "+j.role+" "+j.platform).toLowerCase().includes(q)&&(filter==="Todos"||j.status===filter));
$("navCount").textContent=jobs.length;$("totalStat").textContent=jobs.length;$("appliedStat").textContent=jobs.filter(j=>["Postulado","Entrevista","Contratado"].includes(j.status)).length;$("interviewStat").textContent=jobs.filter(j=>j.status==="Entrevista").length;$("recommendedStat").textContent=jobs.filter(j=>j.evaluation.decision==="POSTULAR").length;
$("jobList").innerHTML=shown.length?shown.map(j=>`<article class="card job"><div class="jobinfo"><b class="${j.evaluation.score>=68?"sg":j.evaluation.score>=45?"sw":"sb"}">${j.evaluation.score}</b><div><p>${escapeHtml(j.company||"Empresa no informada")} · ${escapeHtml(j.platform)}</p><h2>${escapeHtml(j.role||"Puesto sin título")}</h2><span>${escapeHtml(j.mode)} · ${escapeHtml(j.location||"Ubicación no informada")} · ${new Date(j.date).toLocaleDateString("es-AR")}</span></div></div><div class="actions"><select data-status="${j.id}">${["Pendiente","Postulado","Entrevista","Rechazado","Contratado"].map(s=>`<option ${s===j.status?"selected":""}>${s}</option>`).join("")}</select>${j.url?`<a href="${encodeURI(j.url)}" target="_blank" rel="noopener">Abrir ↗</a>`:""}<button class="delete" data-delete="${j.id}">Eliminar</button></div></article>`).join(""):`<div class="card emptyjobs"><h2>Sin ofertas para mostrar</h2><p>Evaluá una oferta o cambiá los filtros.</p></div>`;
document.querySelectorAll("[data-status]").forEach(s=>s.onchange=()=>{const j=jobs.find(x=>x.id===s.dataset.status);j.status=s.value;persist()});document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{if(confirm("¿Eliminar esta oferta?")){jobs=jobs.filter(x=>x.id!==b.dataset.delete);persist()}})}
$("search").oninput=renderJobs;$("statusFilter").onchange=renderJobs;
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$("exportJson").onclick=()=>download(new Blob([JSON.stringify({version:1,jobs},null,2)],{type:"application/json"}),"postular-respaldo.json");
$("exportCsv").onclick=()=>{const esc=v=>'"'+String(v??"").replaceAll('"','""')+'"',h=["Empresa","Puesto","Estado","Decisión","Puntaje","Plataforma","Modalidad","Ubicación","Sueldo","URL","Fecha"],rows=jobs.map(j=>[j.company,j.role,j.status,j.evaluation.decision,j.evaluation.score,j.platform,j.mode,j.location,j.salary,j.url,j.date.slice(0,10)]);download(new Blob(["\ufeff"+[h,...rows].map(r=>r.map(esc).join(",")).join("\n")],{type:"text/csv"}),"postulaciones.csv")};
$("importJson").onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);jobs=Array.isArray(d)?d:d.jobs;if(!Array.isArray(jobs))throw 0;persist();toast("Respaldo importado")}catch{toast("Archivo no válido")}};r.readAsText(file)};
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2400)}renderJobs();